### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by rgiordan** [paulgovan/BayesianNetwork#6]
This issue is for https://github.com/openjournals/joss-reviews/issues/425

There doesn't seem to be an automated way to test whether the shiny app is working as expected.  It seems to me that it would be good to have some tests to check, for example, for breaking changes to the shiny or bnlearn API.

I appreciate that it's not always easy to test web interfaces, and I'm not sure what would be best -- I haven't developed in shiny myself!  But I did find [RSelenium](https://cran.r-project.org/web/packages/RSelenium/vignettes/shinytesting.html), which says that solutions are out there.

**Comment by paulgovan** [comment]
Agreed. Unit tests are difficult in shiny, but recently the [shinytest](https://github.com/rstudio/shinytest) package was released, which looks like a possible solution. This may take a while, but I'll work to incorporate tests in the package.

**Comment by paulgovan** [comment]
Ok I've added tests for the app's basic functionality via the `shinytest` package. `shinytest` is still under development, so the dev version must be installed from GitHub:

`
devtools::install_github("rstudio/shinytest")
`

To run the tests, navigate to the package directory and run:

`
shinytest::testApp("inst/bn")
`

There may be some slight differences between some of the image snapshots due to the randomness of the d3 graphics, but the tests should pass otherwise.

**Comment by paulgovan** [comment]
Ok I've integrated testing with travis as of commit [https://github.com/paulgovan/BayesianNetwork/commit/d53283cfad5b7001e161f6c762f82bca4a19edac](https://github.com/paulgovan/BayesianNetwork/commit/d53283cfad5b7001e161f6c762f82bca4a19edac). Note that this testing framework is still under development, and I will be looking to add more details in the future.
