### ISSUE TITLE
paper.md attributions

### ISSUE THREAD

**Issue by rgiordan** [paulgovan/BayesianNetwork#7]
https://github.com/openjournals/joss-reviews/issues/425

The review has the following checkbox, which is not fulfilled by the current paper.md: "Authors: Does the paper.md file include a list of authors with their affiliations?"  Somewhat relatedly, in my opinion, it might be made clearer in the paper that you're providing a ```shiny``` frontend to ```bnlearn``` rather than implementing the learning algorithms yourself.  Although you do very prominently say it's "powered" by ```bnlearn```, I feel it is best to be as clear as possible with author attribution!

**Comment by paulgovan** [comment]
Agreed as well. Added (fixed) affiliation and attempted to provide clear credit to the package.

**Comment by katyhuff** [comment]
Just a note, in order to communicate that something is fixed, it's common to comment as you have above. However, that comment often includes a link to either a PR, or the merged commit that fixes the issue. In this case, I think it was probably this commit (https://github.com/paulgovan/BayesianNetwork/commit/fb54626f85ffc6a2f7378f951561d73d7400aea8#diff-60426898a850f648abeda63b199792cc) that solved the issue.

**Comment by paulgovan** [comment]
Yes, please reference commits [https://github.com/paulgovan/BayesianNetwork/commit/fb54626f85ffc6a2f7378f951561d73d7400aea8](https://github.com/paulgovan/BayesianNetwork/commit/fb54626f85ffc6a2f7378f951561d73d7400aea8) and [https://github.com/paulgovan/BayesianNetwork/commit/7b29b4df7aa5d947822b5dee43a9a77dda34545b](https://github.com/paulgovan/BayesianNetwork/commit/7b29b4df7aa5d947822b5dee43a9a77dda34545b) on this fix.
